// ═══════════════════════════════════════════
// SETUP — config generation, CI bootstrap, GHA workflow
// ═══════════════════════════════════════════

use crate::progress::format_elapsed;
use crate::project::ProjectProfile;
use colored::Colorize;

pub fn generate_config(output: &str, profile: &ProjectProfile) {
    let config = format!(
        r#"# .quality.toml — CodeMetrics quality thresholds
# Auto-generated for: {ecosystem}
# Used by: codemetrics check . and codemetrics run .
# Run `codemetrics init` at any time to regenerate with updated detection.

[project]
ecosystem = "{ecosystem}"
test_cmd = {test_cmd}
coverage_cmd = {coverage_cmd}
lcov_path = "{lcov_path}"

[crap]
# CRAP = complexity^2 * (1 - coverage)^3 + complexity. Lower is better.
max_avg = {max_crap}

[debt]
max_markers = {max_debt}
types = ["TODO", "FIXME", "HACK", "XXX"]

[doc_coverage]
min_pct = {min_doc}

[complexity]
max_violations = {max_complexity}

[duplication]
max_duplicates = 0
min_lines = 3

[skip]
checks = []
"#,
        ecosystem = profile.ecosystem,
        test_cmd = serde_json::to_string(&profile.test_cmd).unwrap_or_default(),
        coverage_cmd = serde_json::to_string(&profile.coverage_cmd).unwrap_or_default(),
        lcov_path = profile.lcov_path,
        max_crap = profile.max_crap,
        max_debt = profile.max_debt,
        min_doc = profile.min_doc,
        max_complexity = profile.max_complexity_violations,
    );
    std::fs::write(output, config).expect("Failed to write config");
}

pub fn build_gha_workflow(profile: &ProjectProfile) -> String {
    let coverage_step = if profile.is_coverage_available() {
        let cmd = profile.coverage_cmd.join(" ");
        format!(
            r#"      - name: Collect coverage
        run: {cmd}
"#,
            cmd = cmd
        )
    } else {
        String::new()
    };

    let lcov_flag = if !profile.lcov_path.is_empty() {
        format!(" --coverage {}", profile.lcov_path)
    } else {
        String::new()
    };

    format!(
        r#"name: CodeMetrics Quality Gate
# Generated by: codemetrics init --ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2

      - name: Build CodeMetrics
        run: cargo build --release -p codemetrics-cli

      - name: Run tests
        run: {test_cmd}

{coverage_step}
      - name: Quality check
        run: ./target/release/codemetrics check .{lcov_flag} --format text

      - name: Full audit (SARIF)
        run: |
          ./target/release/codemetrics run . --format sarif \
            --baseline .codemetrics-baseline.sarif \
            > quality-results.sarif

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: quality-results.sarif
          category: codemetrics

      - name: Update baseline on main
        if: github.ref == 'refs/heads/main'
        run: |
          mv quality-results.sarif .codemetrics-baseline.sarif
          ./target/release/codemetrics history record
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .codemetrics-baseline.sarif .codemetrics-history/ || true
          git commit -m "chore: update quality baseline [ci skip]" || true
          git push origin HEAD || true
    permissions:
      security-events: write
      contents: write
"#,
        test_cmd = profile.test_cmd.join(" "),
        coverage_step = coverage_step,
        lcov_flag = lcov_flag,
    )
}

/// `codemetrics init --ci`: detect project, write config, install hook, write GHA workflow,
/// seed baseline, record first history entry.
pub fn init_ci(config_path: &str, profile: &ProjectProfile) -> i32 {
    let mut ok = true;

    // 1. Write .quality.toml
    {
        let t = std::time::Instant::now();
        generate_config(config_path, profile);
        eprintln!(
            "  {} Wrote {}  ({})",
            "✓".green().bold(),
            config_path.cyan(),
            format_elapsed(t.elapsed()).bright_black()
        );
    }

    // 2. Install pre-commit hook
    {
        let t = std::time::Instant::now();
        let hook_result = crate::hooks::install_hooks_impl(".", false, profile);
        if hook_result == 0 {
            eprintln!(
                "  {} Installed pre-commit hook  ({})",
                "✓".green().bold(),
                format_elapsed(t.elapsed()).bright_black()
            );
        } else {
            eprintln!(
                "  {} Could not install pre-commit hook (not a git repo?)",
                "!".yellow().bold()
            );
        }
    }

    // 3. Write GitHub Actions workflow
    {
        let t = std::time::Instant::now();
        let gha_dir = ".github/workflows";
        if let Err(e) = std::fs::create_dir_all(gha_dir) {
            eprintln!(
                "  {} Could not create {}: {}",
                "!".yellow().bold(),
                gha_dir,
                e
            );
            ok = false;
        } else {
            let workflow_path = format!("{}/codemetrics.yml", gha_dir);
            let workflow = build_gha_workflow(profile);
            match std::fs::write(&workflow_path, workflow) {
                Ok(_) => eprintln!(
                    "  {} Wrote {}  ({})",
                    "✓".green().bold(),
                    workflow_path.cyan(),
                    format_elapsed(t.elapsed()).bright_black()
                ),
                Err(e) => {
                    eprintln!(
                        "  {} Could not write {}: {}",
                        "!".yellow().bold(),
                        workflow_path,
                        e
                    );
                    ok = false;
                }
            }
        }
    }

    // 4. Seed baseline
    let seed =
        crate::progress::run_with_spinner("seeding quality baseline (this runs all tools)", || {
            std::process::Command::new(std::env::current_exe().unwrap_or("codemetrics".into()))
                .args(["run", ".", "--format", "sarif", "--no-fail-on-regression"])
                .output()
        });
    match seed {
        Ok(out) => {
            let sarif = String::from_utf8_lossy(&out.stdout);
            match std::fs::write(".codemetrics-baseline.sarif", sarif.as_bytes()) {
                Ok(_) => eprintln!("  {} Wrote .codemetrics-baseline.sarif", "✓".green().bold()),
                Err(e) => {
                    eprintln!("  {} Could not write baseline: {}", "!".yellow().bold(), e);
                    ok = false;
                }
            }
        }
        Err(e) => {
            eprintln!(
                "  {} Baseline seeding skipped (codemetrics not on PATH yet): {}",
                "!".yellow().bold(),
                e
            );
        }
    }

    // 5. Record initial history entry
    let history_dir = ".codemetrics-history";
    if std::fs::create_dir_all(history_dir).is_ok() {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        let entry = serde_json::json!({
            "ts": ts,
            "event": "init",
            "ecosystem": profile.ecosystem.to_string(),
            "passed": 0u64,
            "failed": 0u64,
        });
        let path = format!("{}/{}.jsonl", history_dir, ts);
        let _ = std::fs::write(&path, format!("{}\n", entry));
        println!("  {} Recorded initial history entry", "[✓]".green().bold());
    }

    eprintln!();
    if ok {
        eprintln!("  {} Setup complete — CI is ready.", "✓".green().bold());
    } else {
        eprintln!(
            "  {} Setup completed with warnings. Check messages above.",
            "!".yellow().bold()
        );
    }
    eprintln!();
    eprintln!("  {} Next steps:", "▶".cyan().bold());
    eprintln!(
        "    1. {} codemetrics .          {}",
        "$".bright_black(),
        "— verify everything passes locally".bright_black()
    );
    eprintln!(
        "    2. {} codemetrics report .         {}",
        "$".bright_black(),
        "— open the HTML audit report in your browser".bright_black()
    );
    eprintln!(
        "    3. {} git push                     {}",
        "$".bright_black(),
        "— CI runs automatically on next push".bright_black()
    );
    eprintln!(
        "    4. {} codemetrics watch . --full   {}",
        "$".bright_black(),
        "— live feedback during development".bright_black()
    );
    eprintln!();
    0
}
